pub const LANGUAGE: &str = "Solidity"; // | Solidity | Starknet Cairo | Arbitrum Stylus | other...
pub const MODEL_ENV_KEY_NAME: &str = "OPENAI_API_KEY"; // OPENAI_API_KEY, ANTHROPIC_API_KEY, GEMINI_API_KEY, DEEPSEEK_API_KEY, other...
pub const TEMPERATURE: f64 = 0.0; // Temperature controls how creative/predictive the AI's output is. Temperature range for OpenAI is [0-2]...
pub const VALID_MODELS: [&str; 2] = ["o1-mini", "gpt-4o-mini"]; // Currently supported AI models

//pub const MODEL_OPENAI: &str = "gpt-4o-mini"; // o1-mini, gpt-4o-mini, claude-3-haiku-20240307, gemini-1.5-flash-latest, llama3-8b-8192, deepseek-chat, other...
